### ISSUE TITLE
[autonity-demo] Add chart for epirus-free

### ISSUE THREAD

**Issue by eastata** [clearmatics/charts-ose-helm3#18]
As a user, developer
I want Blockchain Explorer for Autonity
So that try to use https://github.com/blk-io/epirus-free

### Acceptance criteria
- Autonity support
- Helm chart that could be used under umbrella charts with `autonity-demo`

Related on https://github.com/clearmatics/www-devops/issues/13

**Comment by shapeshed** [comment]
so initially they will bring up an instance on their infrastructure for us to evaluate the functionality

**Comment by eastata** [comment]
> @eastata Confirmed with @shapeshed that this is still relevant. Migrating issue to the new [clearmatics/charts-ose-helm3](https://github.com/clearmatics/charts-ose-helm3/) repository.

I'm not sure. We have deployed web3lab explorer using image from AWS marketplace. 
There is a HOWTO: https://github.com/clearmatics/block-explorer
As far as I assume it is their common way to delivery it.
So, we not need deploy it into kubernetes and write a chart

**Comment by Klazomenai** [comment]
Not following up with the Epirus block explorer. Closing as won't fix.
