### ISSUE TITLE
[autonity-demo] Implement sigmaroot-e2e-tests

### ISSUE THREAD

**Issue by eastata** [clearmatics/charts-ose-helm3#82]
### Description
Implement the sigmaroot-e2e-tests framework for the autonity-demo chart as part of pipeline deployments

### Acceptance criteria
* [ ] Extend GitHub Actions to include the sigmaroot-e2e-tests set of scripts as part of the workflow

### Related issues
- clearmatics/charts-ose#23

**Comment by Klazomenai** [comment]
@eastata Can you please flesh out this ticket with a full description of how the e2e stack would fit into the autonity-demo chart, an acceptance criteria to understand the work required and link or open any related issues.

**Comment by eastata** [comment]
It is not related with `sigmaroot-e2e-tests` stack
I would like to keep on hold this issue until anybody will define use cases for this product

**Comment by Klazomenai** [comment]
Closing as retired.
