### ISSUE TITLE
[autonity-network] Configuration Changes for the coming autonity 0.7 release

### ISSUE THREAD

**Issue by Jason-Zhangxin-Chen** [clearmatics/charts-ose-helm3#87]
### Description
Changes of configuration of autonity 0.7.0

1. the “init” sub-command which was used to init the chain is removed. The init step is now combined (also in steps) with the autonity start with a new flag “--genesis” specifying the genesis json file:
`Name: "genesis",`
`Usage: Path to the genesis json file, the genesis file contains
configuration that defines the first (aka genesis) block of the chain
and also controls how the client behaves. This flag must be provided
the first time a node is run so that the node can initialise its
database with the provided config. Subsequent to the first run, if the
flag is not set, the node will load all configuration from its
database, otherwise the node will verify that the config for the
genesis block exactly matches the genesis block it has in its database
and then see if the configuration that controls client behaviour is
compatible with the configuration in the database. If so the client will
update the configuration that controls client behaviour. This is the
mechanism is used for handling forks.,`
`Value: "",`
for example:
`autonity --datadir “datadirPath” --genesis “genesisFilePath”`

2. flag “--rpc” to be replaced by “--http”:

`   Name:  "http",
   Usage: "Enable the HTTP-RPC server",`

3. flag “--rpcaddr” to be replaced by "--http.addr":

`   Name:  "http.addr",
   Usage: "HTTP-RPC server listening interface",
   Value: node.DefaultHTTPHost,`

4. flag “--rpcport” to be replaced by “--http.port”:

`   Name:  "http.port",
   Usage: "HTTP-RPC server listening port",
   Value: node.DefaultHTTPPort,`

for example:
`autonity --datadir “datadirPath” --genesis “genesisFilePath” --http --http.addr ‘0.0.0.0’ --http.port 8088`

5. flag “--graphql.port” to be removed since graphql service is now depend on http service:

`   Name:  "graphql",
   Usage: "Enable GraphQL on the HTTP-RPC server. Note that GraphQL can only be started if an HTTP server is started as well.",`

to enable graphql:
`
autonity --datadir “datadirPath” --genesis “genesisFilePath” --http --http.addr ‘0.0.0.0’ --http.port 8088 --graphql`

### Acceptance criteria
- [ ] Updated values.yaml file to reflect latest autonity-init image
- [ ] Manually deploy new release to `devops-tools` cluster
- [ ] Keep PR as Draft until soak test until conversation and some basic assurance tests performed with the Autonity team

### Related issues
- Link the new autonity-init issue

**Comment by Klazomenai** [comment]
The below points have already been done in previous work and does not need to be done.
2. flag “--rpc” to be replaced by “--http”:
3. flag “--rpcaddr” to be replaced by "--http.addr":
4. flag “--rpcport” to be replaced by “--http.port”:
5. flag “--graphql.port” to be removed since graphql service is now depend on http service:

**Comment by Klazomenai** [comment]
Recommendation from @eastata is to use update the autonity-init image and release with existing functionality, but the new flag.
```
docker run -ti --rm -v $(pwd)/tmp:/autonity autonity-init --debug=true --account-import-only=true
```
